# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-22 09:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0010_auto_20180616_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetail',
            name='phonenumber',
            field=models.CharField(blank=True, default=1234567891, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number in the format: '+999999999'. Up to 11 digits allowed.", regex='^\\+?1?\\d{9,11}$')]),
            preserve_default=False,
        ),
    ]
